sequence = "cctatgacccgtttatagcaacgctctctatcaagtccacgatgtcgatatgtggtcatatatacgtaagatcattgcacgaaatggcacctccggttcagttgttctgtaataagaattaggttgcggaaagcgcattcgtaatgacaggtaccttaagagatatagagtacttacggcagagtctgtgaaagtgccctctctactatgagcaaaaggttgtgagccacctgtggaagaactataagacaagatctcgcaaggtatgtgccgcatatactacgagttatactatgtaacgttctgatatcctatgcgtcaagcgccgctcggcttggtctattcgcgaggtagcggatttgccagatatcaagcgtgtttacgagtagacagtatacagtagagggagccgctagagttgatgggccgcacaatgtatgtctaatgtcgttattaaatggtgacaatcacctcatactagggaaataatgagttaacactgcagatcctacatgagtaaaacaagacttacttgtgtacaattcggccaaaacctagtcggtggttgtgaccaacgcattcggcgccataaccaccgattcggatcaccagatacaaggaggtagcgttttacgtgctaatcgacgttcgatagcagtgggtgtgaagtggcctacataaaacggacaggatctcctaatcgtgggaatggagtcgtattcctacacataccttttgacgatgccgacccaattcggatgtgcgtagctagctctgcccgcaacgggttgcggagaggacacaatgcgtgttcacactggtgctagtaggatatgccggccggtgctgtggctggtaagacgcgcgatctgagatgagccctagtctggtgtatctggaccgagtttgctagagagggttagtaatctgccactcacgtcaggttgcgacagtcaggatcttaaggacgtgacgagggagtgcgtaggtgtgaagccct"
counter = -1 
for letter in seq:
    print("base", counter, "is', letter)
    counter = counter - 1

print("Sequence has", int(count), "bases.")
